### ISSUE TITLE
Implement specific exceptions

### ISSUE THREAD

**Issue by agoose77** [sjdv1982/seamless#6]

**Comment by sjdv1982** [comment]
Yes, but remember that most exceptions come from processes, and most processes will be async. Right now, transformers are async, although editors are not, since GUIs must run in the main thread. Eventually, async editor kernels and out-of-process transformer and editor kernels will need to be implemented. 
After that, I can imagine some kind of GUI canvas that captures and shows the current exception for each process.

Exceptions that come in the main thread come from 1. (mis-)construction of cells and 2. macros. Macros are in full development, but indeed, the time is ripe to think of specific cell construction exceptions.

**Comment by sjdv1982** [comment]
Will be solved using an error message logging system (using composite cells), scheduled for seamless 0.2.
